export const producers = [
    'Ameredev',
    'Artesia Volumes',
    'Caza',
    'Centennial',
    'Chevron',
    'Chisholm',
    'Cimarex',
    'Concho - Legacy',
    'Concho - Tankless',
    'Devon - LP',
    'Devon - HP',
    'Devon Gathering Volumes',
    'Energen',
    'EOG - HP',
    'EOG - LP',
    'Felix',
    'Lilis',
    'Marathon',
    'Matador',
    'Mewbourne',
    'MRC',
    'Murchison',
    'Others',
    'Taprock',
    'Total SC Processed Volumes',
    'WPX',
    'XTO - Remuda/JR/TW',
    'XTO - Cowboy',
    'XTO - Big Eddy',
    'XTO - Other',
];
